[package]
name = "lumina2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
insta = "1.43.2"
rstest = "0.26.1"
thiserror = "2.0.17"


[dev-dependencies]
mockall = "0.13.1"
