[package]
name = "lumina2"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.8.0", features = ["llvm18-1"] }
insta = "1.46.0"
rstest = "0.26.1"
thiserror = "2.0.17"


[dev-dependencies]
mockall = "0.14.0"
