name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: "always"
  LLVM_PATH: "${{ github.workspace }}/llvm"
  LLVM_VERSION: "18.1"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup
        with:
          llvm-version: ${{ env.LLVM_VERSION }}
          llvm-path: ${{ env.LLVM_PATH }}

      - name: Install cargo-llvm-cov and nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,nextest

      - name: Test with code coverage
        run: |
          cargo llvm-cov nextest --all-features --workspace --lcov --profile=ci --output-path lcov.info
        env:
          LLVM_SYS_181_PREFIX: "${{ env.LLVM_PATH }}"

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          report_type: test_results
          fail_ci_if_error: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          report_type: coverage
          fail_ci_if_error: false

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup
        with:
          llvm-version: ${{ env.LLVM_VERSION }}
          llvm-path: ${{ env.LLVM_PATH }}

      - name: Run clippy
        run: |
          cargo clippy --all-features --all-targets --keep-going -- -D warnings
        env:
          LLVM_SYS_181_PREFIX: "${{ env.LLVM_PATH }}"

  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: streetsidesoftware/cspell-action@v8
        with:
          incremental_files_only: false

  cargo-mutants:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup
        with:
          llvm-version: ${{ env.LLVM_VERSION }}
          llvm-path: ${{ env.LLVM_PATH }}

      - name: Install cargo-mutants and nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-mutants,nextest

      - run: cargo mutants -vV --in-place

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mutants-out
          path: mutants.out

# spell-checker:ignore libtinfo,Swatinem
